version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=root
    volumes:
      - accounting_challenge_data:/var/lib/postgresql/data
    ports:
      - "3307:3306"
  rails:
    build: .
    command: /bin/sh -c "bundle exec rake db:setup; bundle exec rails s -b 0.0.0.0"
    container_name: accounting_challenge
    ports:
      - 3000:3000
    volumes:
      - .:/var/app
    environment:
      - RAILS_ENV=development
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
    links:
      - db
volumes:
  accounting_challenge_data: