default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") %>
  host: db

development:
  <<: *default
  database: accounting_challenge_development

test:
  <<: *default
  database: accounting_challenge_test

production:
  <<: *default
  database: accounting_challenge_production
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
